<?php
return array(
	'version' => 
	array(
		'app' => 
		array(
			'default' => 
			array(
				0 => '001_create_dialler_all_numbers',
				1 => '002_create_dialler_all_logs',
				2 => '003_create_s',
				3 => '004_create_dialler_campaigns',
				4 => '005_create_call_centers',
				5 => '006_create_database_servers',
				6 => '007_create_database_queries',
				7 => '008_create_database_query_tags',
				8 => '009_create_dialler_lists',
				9 => '010_create_data_suppliers',
				10 => '011_create_data_supplier_lists',
				11 => '013_add_title_to_data_supplier_lists',
				12 => '014_add_name_to_data_users',
				13 => '015_add_call_center_id_to_users',
				14 => '016_add_shortcode_to_call_center',
				15 => '017_create_users_log_logins',
				16 => '018_add_status_to_users_log_login',
				17 => '019_delete_field_login_time_from_users_log_logins',
				18 => '020_add_attempted_login_to_users_log_login',
				19 => '021_add_ip_address_to_users_log_logins',
				20 => '022_create_help_topics',
				21 => '023_create_help_tickets',
				22 => '024_create_news',
				23 => '025_create_debtsolv_transfer_logs',
				24 => '026_create_data_supplier_campaigns',
				25 => '027_create_data_supplier_campaigns_data_suppliers',
				26 => '028_create_data_supplier_campaign_lists',
				27 => '029_create_surnames',
				28 => '030_create_towns',
				29 => '031_add_last_town_to_surnames',
				30 => '032_create_selfgenerations',
				31 => '033_create_proxies',
				32 => '034_add_use_count_to_proxies',
				33 => '035_create_proxy_imports',
				34 => '036_create_adam_messages',
				35 => '037_create_adam_announcements',
				36 => '038_create_data_supplier_campaign_lists_duplicates',
				37 => '039_add_dialler_to_data_supplier_campaign_lists_duplicates',
				38 => '040_add_lead_id_to_data_supplier_campaign_lists_duplicates',
				39 => '041_create_tomorrow_list_stats',
				40 => '042_add_dialler_to_tomorrow_list_stats',
				41 => '043_add_campaign_to_tomorrow_list_stats',
				42 => '044_create_lead_tables',
				43 => '045_create_dialler_campaign_calls',
				44 => '046_create_api_users',
				45 => '047_create_printmanager_printers',
				46 => '048_create_printmanager_trays',
				47 => '049_create_printmanager_queues',
				48 => '050_add_api_key_to_call_centers',
				49 => '051_create_calendar_holidays',
				50 => '052_create_staffs',
				51 => '053_create_staff_departments',
				52 => '054_add_center_id_to_staff',
				53 => '055_add_department_id_to_staff',
				54 => '056_create_telesales_report_values',
				55 => '057_add_pack_out_commission_to_telesales_report_values',
				56 => '058_add_pack_out_bonus_to_telesales_report_values',
				57 => '059_add_payment_percentage_to_telesales_report_values',
				58 => '060_create_dialler_current_agents',
				59 => '061_create_user_centers',
			),
		),
		'module' => 
		array(
		),
		'package' => 
		array(
			'crm' => 
			array(
				0 => '001_create_crm_client_details',
				1 => '002_create_crm_client_access_log',
				2 => '003_create_crm_type_client_status',
				3 => '004_create_crm_type_countries',
				4 => '005_create_crm_client_products',
				5 => '006_drop_crm_client_access_log',
				6 => '007_alter_crm_client_details_add_created',
				7 => '008_create_crm_client_partner_details',
				8 => '009_alter_crm_client_partner_detailsautoid',
			),
		),
		'subpackage' => 
		array(
			'crm_invoice' => 
			array(
				0 => '001_create_crm_invoices',
				1 => '002_alter_crm_invoices_addvat',
			),
			'crm_ppi' => 
			array(
				0 => '001_create_crm_ppi_claims',
				1 => '002_create_crm_ppi_clients',
				2 => '003_create_crm_ppi_correspondence',
				3 => '004_create_crm_ppi_refund',
				4 => '005_create_crm_type_ppi_claim_stage',
				5 => '006_create_crm_type_ppi_claim_status',
				6 => '007_create_crm_type_ppi_refund_method',
				7 => '008_alter_crm_ppi_clients_add_packs',
				8 => '009_alter_crm_ppi_claims_add_account_info',
				9 => '010_alter_crm_type_ppi_claim_status_change_name',
				10 => '011_alter_crm_ppi_correspondence_addfields',
				11 => '012_alter_crm_ppi_clients_packout_fields',
				12 => '013_alter_crm_ppi_correspondence_changenotes',
				13 => '014_alter_crm_ppi_claims_addedsignatory',
				14 => '015_alter_crm_ppi_clients_addpartner',
				15 => '016_alter_crm_ppi_claims_invoice_id',
				16 => '017_alter_crm_ppi_claims_change_ac',
				17 => '018_alter_crm_ppi_refund_removecols',
				18 => '019_create_crm_type_debt',
				19 => '020_alter_crm_ppi_claims_debttype',
				20 => '021_alter_crm_ppi_refund_invoiceid',
			),
		),
	),
	'folder' => 'migrations/',
	'table' => 'migration',
);
